# Base image
FROM node:16

# Set working directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy application code
COPY . .

# Create uploads directory
RUN mkdir -p uploads/profile-photos

# Expose port
EXPOSE 5000

# Start application
CMD ["npm", "run", "dev"]